# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AR_Evacuation_Beacon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AR_Evacuation_Beacon
  pod 'TensorFlowLiteSwift'

end
