package com.example.aos_ar_evacuation_beacon.constant

enum class AdjacentCell(val cell: List<Any>) {
   A01(listOf(Position.E01, Position.R04, Position.A02, Position.R02)),
   A02(listOf(Position.A01, Position.unknown, Position.A03, Position.A08)),
   A03(listOf(Position.A02, Position.R01, Position.A04, Position.A08)),
   A04(listOf(Position.A03, Position.unknown, Position.A05, listOf(Position.A08, Position.A09))),
   A05(listOf(Position.A04, Position.R05, Position.A06, Position.A09)),
   A06(listOf(Position.A05, Position.unknown, Position.A07, Position.A09)),
   A07(listOf(Position.A06, Position.unknown, Position.H02, Position.A10)),
   A08(listOf(listOf(Position.A02, Position.A03), listOf(Position.A03, Position.A04), Position.A09, Position.unknown)),
   A09(listOf(Position.A08, listOf(Position.A04, Position.A05, Position.A06, Position.A07), listOf(Position.A10, Position.A11, Position.A07), Position.unknown)),
   A10(listOf(Position.A09, Position.A07, Position.E03, listOf(Position.A11, Position.E03))),
   A11(listOf(Position.A09, Position.A10, Position.E03, Position.E03)),
   E01(listOf(Position.unknown, listOf(Position.S01, Position.S02), Position.A01, Position.R03)),
   E02(listOf(Position.unknown, Position.unknown, Position.unknown, listOf(Position.S07, Position.S06))),
   E03(listOf(Position.A11, Position.unknown, Position.unknown, Position.unknown)),
   R01(listOf(Position.unknown, Position.unknown, Position.unknown, listOf(Position.A03, Position.A04, Position.A02))),
   R02(listOf(Position.unknown, listOf(Position.A01, Position.A02), Position.unknown, Position.unknown)),
   R03(listOf(Position.unknown, Position.E01, Position.unknown, Position.unknown)),
   R04(listOf(Position.unknown, Position.unknown, Position.unknown, listOf(Position.A01, Position.A02))),
   R05(listOf(listOf(Position.A04, Position.A05), Position.unknown, listOf(Position.A05, Position.A06, Position.A07), listOf(Position.A05, Position.A06, Position.A04))),
   S01(listOf(Position.unknown, Position.unknown, Position.unknown, Position.E01)),
   S02(listOf(Position.unknown, Position.S03, Position.unknown, Position.E01)),
   S03(listOf(Position.unknown, Position.unknown, Position.unknown, listOf(Position.S02, Position.S04))),
   S04(listOf(Position.unknown, Position.S03, Position.unknown, Position.H01)),
   S05(listOf(Position.H01, Position.H01, Position.H01, Position.S06)),
   S06(listOf(Position.S05, Position.unknown, Position.unknown, Position.H02)),
   S07(listOf(Position.unknown, Position.E02, Position.unknown, Position.H02)),
   S08(listOf(Position.unknown, Position.E02, Position.unknown, Position.S09)),
   S09(listOf(Position.U01, Position.S08, Position.unknown, Position.unknown)),
   U01(listOf(Position.unknown, Position.unknown, Position.S09, Position.unknown)),
   H01(listOf(Position.unknown, Position.S04, Position.unknown, Position.unknown)),
   H02(listOf(Position.A07, listOf(Position.S07, Position.S06), Position.unknown, Position.unknown))
}